apiVersion: v1
kind: Namespace
metadata:
  name: coredns
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: dns
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
