apiVersion: batch/v1
kind: Job
metadata:
  name: restic-repo-init
  namespace: backup
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300  # 5 min timeout
  template:
    spec:
      serviceAccountName: restic-backup
      restartPolicy: OnFailure
      containers:
        - name: restic
          image: restic/restic:0.18.1
          command:
            - /bin/sh
            - -c
            - |
              set -e

              # Check if the repo already exists
              if restic snapshots --no-lock > /dev/null 2>&1; then
                echo "Restic repository already initialized."
                restic snapshots --latest 5
              else
                echo "Initializing restic repository..."
                restic init
                echo "Repository initialized successfully."
              fi
          envFrom:
            - configMapRef:
                name: restic-config
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: b2-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: b2-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: b2-credentials
                  key: RESTIC_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
