apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silver-springs-state
  namespace: silver-springs-watch
  labels:
    app.kubernetes.io/name: silver-springs-watch
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
