apiVersion: batch/v1
kind: CronJob
metadata:
  name: icloudpd-sync
  namespace: photo-sync
spec:
  schedule: "0 3 1 * *"  # 3 AM on 1st of each month
  timeZone: "America/Edmonton"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 86400  # 24h timeout
      template:
        spec:
          serviceAccountName: icloudpd
          restartPolicy: OnFailure
          containers:
            - name: icloudpd
              image: boredazfcuk/icloudpd:latest
              command:
                - /bin/sh
                - -c
                - |
                  /opt/icloudpd/bin/icloudpd --directory /photos/icloud-import \
                    --username $(cat /credentials/username) \
                    --password $(cat /credentials/password) \
                    --cookie-directory /config \
                    --folder-structure "{:%Y/%m}" \
                    --until-found 50 \
                    --set-exif-datetime \
                    --no-progress-bar
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
                  readOnly: true
                - name: config
                  mountPath: /config
                - name: photos
                  mountPath: /photos
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "1000m"
          volumes:
            - name: credentials
              secret:
                secretName: icloud-credentials
            - name: config
              persistentVolumeClaim:
                claimName: icloudpd-config
            - name: photos
              persistentVolumeClaim:
                claimName: icloud-photos
