apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-data-pvc
  namespace: wishlist
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: wishlist-data-pv
