apiVersion: v1
kind: PersistentVolume
metadata:
  name: wishlist-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wishlist-data-pvc
    namespace: wishlist
  hostPath:
    path: /var/lib/wishlist-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
