apiVersion: v1
kind: PersistentVolume
metadata:
  name: icloud-photos-immich
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: icloud-immich
  hostPath:
    path: /var/mnt/icloud-photos
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
