apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloud-import
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  # This will create a separate PVC in immich namespace
  # We'll use hostPath to share the same directory with photo-sync
