apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloud-photos
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: icloud-immich
  volumeName: icloud-photos-immich
