apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloud-import
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: icloud-shared
  volumeName: icloud-photos-shared
