apiVersion: v1
kind: PersistentVolume
metadata:
  name: upsnap-data-pv
  labels:
    app.kubernetes.io/name: upsnap
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/upsnap-data
    type: DirectoryOrCreate
