apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upsnap-data-pvc
  namespace: upsnap
  labels:
    app.kubernetes.io/name: upsnap
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
