apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data-pvc
  namespace: homebox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: homebox-data-pv
