apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebox-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: homebox-data-pvc
    namespace: homebox
  hostPath:
    path: /var/lib/homebox-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
